database_name: cms_complete
user_name: postgres
password: vigilante
features:
        - 'npi'
        - 'nppes_provider_city'
        - 'nppes_provider_last_org_name'
        - 'nppes_provider_street1'
        - 'nppes_provider_street2'
        - 'nppes_provider_zip'
        - 'nppes_provider_state'
        - 'line_srvc_cnt'
        - 'bene_unique_cnt'
        - 'bene_day_srvc_cnt'
        - 'average_medicare_allowed_amt'
        - 'average_submitted_chrg_amt'
        - 'average_medicare_payment_amt'
